FOODS/urls.py
from django.urls import path
from . import views


app_name = "FOOD"

urlpatterns = [
	path('list/', views.food_list, name="LIST"),
	path('<slug:slug>/', views.food_recipe, name="RECIPE"),
]

WBCookBook/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name="HOME"),
    path('food/', include('FOODS.urls')),
    path('admin/', admin.site.urls),
]

FOODS/models.py
from django.db import models
from django.template.defaultfilters import slugify #slugify a string for navigating

# Create your models here.

class Food(models.Model):
	name = models.CharField(max_length=200, default="PIZZA", unique=True)
	price = models.CharField(max_length=200, default="20.2")
	servings = models.CharField(max_length=200, default="4")
	preptime = models.CharField(max_length=200, default="50")
	foodType = models.CharField(max_length=200, default="50")

	ingredients = models.TextField()
	instructions = models.TextField()

	banner = models.CharField(max_length=800)
	slug = models.SlugField(blank=True)
	added_at = models.DateTimeField(auto_now_add=True)

	# operations when an instance of Food is save or rather when it is in the process of saving the instance
	def save(self, *args, **kwargs):
		# if the instance slug has a value it will save
		# if instance slug has no value, a value will be set, the value will be the Post title in lowercase format
		if self.slug:
			pass
		else:
			self.slug = slugify(self.name.lower())

		# super() is directed to the specific instance being manipulated
		super().save(*args, **kwargs)

	def __str__(self)->str:
		return self.name

FOODS/views.py
from django.shortcuts import render
from .models import Food


def food_list(request):
	foods = Food.objects.all()


	return render(request, 'FOODS/FoodList.html',{
		'foods':foods
		})

def food_recipe(request, slug):
	food = Food.objects.get(slug=slug)

	return render(request, 'FOODS/FoodRecipe.html',{
		'food':food
		})

WBCookBook/views.py
from django.shortcuts import render


def home(request):
	return render(request, 'home.html')

FOODS/templates/FOODS/FoodList.html
{% extends "structure.html" %}



{% block title %}
	All Food | CookBook
{% endblock %}

{% block content %}
	<div id="food-page">
		<div class="foods-container">
			{% for food in foods %}
				<div class="food">
					<div class="banner">
						<img src="{{food.banner}}" alt="">
					</div>
					<h3>{{food.name}}</h3>
					<button>
						<a href="{% url 'FOOD:RECIPE' slug=food.slug %}">VIEW RECIPE</a>
					</button>
				</div>
			{% endfor %}
		</div>		
	</div>

{% endblock %}

FOODS/templates/FOODS/FoodRecipe.html
{% extends "structure.html" %}



{% block title %}
	{{food.name}} | CookBook
{% endblock %}


{% block content %}
	<div id="food-recipe">
		<a href="{% url 'FOOD:LIST' %}">Back</a>
		<h1>{{food.name}}</h1>


		<div class="info-container">
			<div class="top">

			<div class="metas">
				<img src="{{food.banner}}" alt="">
				<p>
					<span class="prep">{{food.preptime}} Preparation Time</span>
					<span class="serve">Servings: {{food.servings}}</span>
					<span class="type">Food: {{food.foodType}}</span>
					<span class="price">Price: {{food.price}}</span>
				</p>
			</div>

			<div class="ingre">
				<h3>Recipe Ingredients</h3>
				<p>{{food.ingredients}}</p>
			</div>				
			</div>

			<div class="bottom">
				<h3>Instructions</h3>
				<p>{{food.instructions}}</p>
			</div>




		</div>



	</div>	
{% endblock %}

templates/home.html
{% extends 'structure.html' %}


{% block title %}
	Home | CookBook
{% endblock %}


{% load static %}
{% block content %}

	<div class="mirror"></div>

	<div id="home-page">
		<div class="content">
			<img src="{% static 'assets/CookBookBrand.png' %}" alt="">
			<h3>Your Daily Dose of Delicious.</h3>
			<button>
				<a href="{% url 'FOOD:LIST' %}">SEE FOODS</a>
			</button>
		</div>
	</div>
{% endblock %}

templates/structure.html
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>
		{% block title %}
			{# TITLE GOES HERE #}
		{% endblock %}
	</title>
	{% load static %}
	{% block style %}
		<link rel="stylesheet" href="{% static 'styles/master.css' %}">
	{% endblock %}

</head>

<body>

<nav class="Navigation">
	<div class="mark">
		<img src="{% static 'assets/CookBookBrand.png' %}" alt="brand">
		<h1>WareBar's Cook Book</h1>
	</div>

	<ul class="nav-list">
		<li>
			<a href="{% url 'HOME' %}">Home</a>
		</li>
	</ul>



</nav>


<main>
	{% block content %}
		{# CONTENT GOES HERE #}
	{% endblock %}
</main>

	
</body>

</html>